// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShopApp.Data;
using System;

namespace ShopApp.Data.Migrations.AddDataDb
{
    [DbContext(typeof(AddDataDbContext))]
    partial class AddDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopApp.Models.DataViewModels.AddDataViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("brand")
                        .HasMaxLength(30);

                    b.Property<string>("classify")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime");

                    b.Property<string>("createuser")
                        .HasMaxLength(50);

                    b.Property<string>("imageurl")
                        .HasMaxLength(255);

                    b.Property<string>("model")
                        .HasMaxLength(50);

                    b.Property<string>("modelmum")
                        .HasMaxLength(50);

                    b.Property<string>("remark")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime");

                    b.Property<string>("updateuser")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("AddDataViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
